package com.bistpicker.mobile.data.local

import androidx.room.Dao
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * Read-only DAO over the snapshot SQLite. The DB is regenerated by Python
 * cron and atomically swapped in by [SnapshotApplier]; the APK never writes
 * through this DAO.
 *
 * Every "list" query exposes a [Flow] so screens recompose automatically
 * when the snapshot rolls over. Detail queries are suspending one-shots
 * because the detail screen explicitly observes a single ticker.
 */
@Dao
interface SnapshotDao {

    // ── Metadata + home ────────────────────────────────────────────────

    @Query("SELECT * FROM snapshot_metadata WHERE id = 1")
    fun observeMetadata(): Flow<SnapshotMetadataEntity?>

    @Query("SELECT * FROM snapshot_metadata WHERE id = 1")
    suspend fun getMetadata(): SnapshotMetadataEntity?

    @Query("SELECT * FROM home_summary WHERE id = 1")
    fun observeHomeSummary(): Flow<HomeSummaryEntity?>

    // ── Open positions / portfolio history ─────────────────────────────

    @Query("SELECT * FROM open_positions ORDER BY sort_order")
    fun observeOpenPositions(): Flow<List<OpenPositionEntity>>

    @Query("SELECT * FROM portfolio_history ORDER BY exit_date DESC, sort_order")
    fun observePortfolioHistory(): Flow<List<PortfolioHistoryEntity>>

    @Query("SELECT * FROM scoring_latest WHERE alpha_core_eligible = 1 ORDER BY ranking_score DESC LIMIT :limit")
    fun observeTopScoring(limit: Int): Flow<List<ScoringLatestEntity>>

    // ── Scoring list (Liste tab) ───────────────────────────────────────

    /** Used by the Scoring screen with paging. Filtered + sorted in SQL
     * to keep memory low when the user scrolls the full ~800-stock list. */
    @Query(
        """
        SELECT * FROM scoring_latest
        WHERE
          (:onlyAlphaCore = 0 OR alpha_core_eligible = 1)
          AND (:onlyAlphaX = 0 OR alpha_x_eligible = 1)
          AND (:onlyBist100 = 0 OR is_bist100 = 1)
          AND (:sector IS NULL OR sector = :sector)
          AND (:risk IS NULL OR risk = :risk)
          AND (:minScore IS NULL OR (ranking_score IS NOT NULL AND ranking_score >= :minScore))
          AND (
            :search IS NULL
            OR ticker LIKE '%' || :search || '%'
            OR name LIKE '%' || :search || '%'
          )
        ORDER BY
          CASE WHEN ranking_score IS NULL THEN 1 ELSE 0 END,
          ranking_score DESC,
          ticker ASC
        LIMIT :limit OFFSET :offset
        """
    )
    suspend fun queryScoring(
        onlyAlphaCore: Int,
        onlyAlphaX: Int,
        onlyBist100: Int,
        sector: String?,
        risk: String?,
        minScore: Double?,
        search: String?,
        limit: Int,
        offset: Int,
    ): List<ScoringLatestEntity>

    @Query(
        """
        SELECT COUNT(*) FROM scoring_latest
        WHERE
          (:onlyAlphaCore = 0 OR alpha_core_eligible = 1)
          AND (:onlyAlphaX = 0 OR alpha_x_eligible = 1)
          AND (:onlyBist100 = 0 OR is_bist100 = 1)
          AND (:sector IS NULL OR sector = :sector)
          AND (:risk IS NULL OR risk = :risk)
          AND (:minScore IS NULL OR (ranking_score IS NOT NULL AND ranking_score >= :minScore))
          AND (
            :search IS NULL
            OR ticker LIKE '%' || :search || '%'
            OR name LIKE '%' || :search || '%'
          )
        """
    )
    suspend fun countScoring(
        onlyAlphaCore: Int,
        onlyAlphaX: Int,
        onlyBist100: Int,
        sector: String?,
        risk: String?,
        minScore: Double?,
        search: String?,
    ): Int

    @Query("SELECT DISTINCT sector FROM scoring_latest WHERE sector IS NOT NULL ORDER BY sector")
    suspend fun listSectors(): List<String>

    // ── Detail screen queries ──────────────────────────────────────────

    @Query("SELECT * FROM scoring_latest WHERE ticker = :ticker LIMIT 1")
    suspend fun getScoring(ticker: String): ScoringLatestEntity?

    @Query("SELECT * FROM companies WHERE ticker = :ticker LIMIT 1")
    suspend fun getCompany(ticker: String): CompanyEntity?

    @Query("SELECT * FROM open_positions WHERE ticker = :ticker LIMIT 1")
    suspend fun getOpenPosition(ticker: String): OpenPositionEntity?

    @Query("SELECT * FROM adjusted_metrics_latest WHERE company_id = :companyId LIMIT 1")
    suspend fun getAdjustedMetrics(companyId: Int): AdjustedMetricsEntity?

    @Query("SELECT * FROM price_history_730d WHERE company_id = :companyId ORDER BY date")
    suspend fun getPriceHistory(companyId: Int): List<PriceHistoryEntity>
}
